### ISSUE TITLE
Buggs Report

### ISSUE THREAD

**Issue by HotelXz** [sant0ro/Yupi#10]
Hi, When i used azure 2.0 before i had one big problem and it is, The both freeze and battle banzai ports dont work good, Same with few old teleporters they dont work, And few works of them works well (new teleports), And can u fix so the proxy works with this emu so i dont need to add it every time i dowload a new update thank u

**Comment by sant0ro** [comment]
Hello, this is not Azure. But can you say again the bugs? I think i understood:

1. Proxy doesn't work, because you need put Proxy ports, directly in Emulator crossdomain Configuration yeah? If yes, can u tell me which file is in Azure Emulator?
2. BattleBanzai and Freeze ports works in Yupi also in Azure 1.0, the unique problem is you need put the Game Scores and Game Timers do Start the Game. Yeah is a little bug, Because in Habbo you can trepass the Gates but nothing happens. Here you can only trepass the gates when the Game is started. I will check this out.

**Comment by HotelXz** [comment]
Here is one exempel of the old azure teleport bug that is annoying: https://gyazo.com/95f6208ad58988c01a3441a2ba42d42c

I tried to go in the teleport but i didnt get out of the another side xd, many of the old teleporters is so 
thanks

**Comment by sant0ro** [comment]
This bug doesn't exists in Yupi. Please here is not place for Azure Bugs.
