### ISSUE TITLE
Room report dont appear on Mod-Tools.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#105]
Look the screenshots.
![2](https://cloud.githubusercontent.com/assets/6734589/15626881/17c7378e-24d1-11e6-94d3-4a1458edc67a.png)
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15626880/17c5ec12-24d1-11e6-9fe9-6a7b88983659.png)

**Comment by ovflowd** [comment]
Closing this Issue. Please stop creating new issues or i will block you at GitHub.

All these Issues already exists if you see correctly the Issues List.

Also i will say only one more time, this issues are related to `NIO` branch and we don't are giving support to `NIO` branch, since is discontinued. `LINUX` branch is the branch that we're developing.

**Comment by ovflowd** [comment]
Anyway, thanks for creating these issues. But please stop Antho. I will say to you, when the development continues to you test the LINUX branch.

Cheers.
