### ISSUE TITLE
Problem with pets interactor.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#114]
All interactor list of pets dont work:
pet_gnomo
pet_monster
pet_bunnyeaster
pet_bunnyevil
pet_bunnylove
pet_bunnydepressed
pet_pigeongood
pet_pigeonevil
pet_demonmonkey

All pets dont apear on my catalogue.

**Comment by ghost** [comment]
Video: http://tinypic.com/player.php?v=2jb41af%3E&s=9#.V5tewBWLS70

**Comment by ovflowd** [comment]
Those pets aren't coded in Yupi. But is really easily to code since Yupi PETS system is dynamic.
![image](https://cloud.githubusercontent.com/assets/12037269/17250663/c4da5cdc-557b-11e6-94b8-6b2fc37a04c4.png)
![image](https://cloud.githubusercontent.com/assets/12037269/17250684/dfd720d8-557b-11e6-9364-669a2f5d788f.png)
![image](https://cloud.githubusercontent.com/assets/12037269/17250700/eafa6c5e-557b-11e6-9f06-3f930ad97787.png)

**Comment by ghost** [comment]
How i found race id on external_variables please ?

**Comment by ovflowd** [comment]
Search for PETS in External_Variables the you will encounter a line with the Pet Races Names separated by Comma. The Pet Races ID's you only can obtain by Packet Logging.

**Comment by ghost** [comment]
Thanks works fine, you are the best ;)

**Comment by ovflowd** [comment]
You're welcome ;)
