### ISSUE TITLE
Problem with rooms config 1/2.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#124]
Bug n°1: This option dont work.
Bug n°2: Wheni check the case, and i reconnect on the client, the case is unchecked.
![1](https://cloud.githubusercontent.com/assets/6734589/17278825/a7077270-5766-11e6-93dd-4391ad7c794b.png)

**Comment by TheDoct0r11** [comment]
Hello, since neither I nor any other team member (at least as far as I know) does speak french, it would be helpful if you could provide a translation of the affected checkbox.

From what I can see right now, this is either a package handling issue or a missing database storage operation. Either way both of those components are currently being redesigned.
