### ISSUE TITLE
Redis - Caching System (very fast)

### ISSUE THREAD

**Issue by necm1** [sant0ro/Yupi#137]
We should use **Redis** for _Caching_ (Redis is the fastest key storage).
http://redis.io/

**Comment by ovflowd** [comment]
We will analyse if is good for us. @Nenji can you say the features of `Redis` ?

**Comment by TheDoct0r11** [comment]
I don't think that we need Redis. NHibernate already got First Level Caching by default and we can additionally activate second level caching, when we get around to do so.

Yupi just uses very few ram on startup, because the cache is a real cache:
On first request, it WILL result in a cache miss, but on subsequent requests (by id), NHibernate should return the data from cache (cache hit).

**Comment by ovflowd** [comment]
As we see, isn't necessary now. Closing Issue.
**If anyone want to open again feel free.**
