### ISSUE TITLE
Some commands doesn't works

### ISSUE THREAD

**Issue by bblackv** [sant0ro/Yupi#28]
Commands:

:disableevents/ :status/ :refresh_catalogue doesn't works. Sorry for my english

**Comment by sant0ro** [comment]
:disableevent is only to when you send an :eventha;:eventalert the user that entered the command :disableevent doesn't received the Hotel Alert. Because some users doesn't like the Flood from Event Alert.

:refresh_catalogue doesn't work? Will check that.

:status is for appear as offline or online in hotel.

**Comment by bblackv** [comment]
Eu entrei em duas contas, uma (rank 1) usei o comando :disableevent e na outra (rank 10) usei o comando :eventha e mesmo assim apareceu

**Comment by sant0ro** [comment]
You verified if disableevent is enabled for rank 1?
Also the Event Alert doesn't must appear for the Rank 1, to the rank 10 can appear, because he didn't typed disableevent.

**Comment by bblackv** [comment]
Yes, i verified it

**Comment by sant0ro** [comment]
Okay i will check.
