### ISSUE TITLE
Pets/Roompets totally bugged & WalkInternalLink

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#53]
- Bug list:
- Interaction.WalkInternalLink not working 
- Interaction.QuickTeleport buggy (the habbo public room teleport arrow)

  (Tested on pixar)
  When you pickup your pets and :reload, they are back
- Horses saddle bugs

- ![IMG](http://i.imgur.com/zTUBzuw.png)
- You can remove a horses saddle, while riding it and stay on the horse
- There is no dismount for a horse (Only picking it up)
- Not sure if this is also in habbo but the horse tail changes when equipping a saddle
- Buggy walking on horses

- ![Gif](https://media.giphy.com/media/QV9jkFd848AMg/giphy.gif)
- The horse moonwalks, randomly sits etc.

**Comment by sant0ro** [comment]
+ WalkInternalLink? What is that?
+ QuickTeleport? What is bugged? The effect?
+ Horse Saddle isn't totally coded.
+ As i said Pets aren't done, i said that to you, and for everyone in dev thread and issues.
+ Yes you can't dismount. Isn't coded i think. Or bad coded.
+ The horse moonwalks, randomly sits etc. WTF?
+ When you pickup pets they go back to inventory, :reload make theys back? Idk why, try first going to other room... Maybe this happens because the room_id from pet's aren't updating.. Weird, (when you pickup need to set 0 or NULL) i will check it.

Addin all this on main issue thread.
