### ISSUE TITLE
Proposal: Use Github API instead of UPDATES.json

### ISSUE THREAD

**Issue by TheDoct0r11** [sant0ro/Yupi#77]
Hello,
you might want to take a look at [this](https://api.github.com/repos/sant0ro/Yupi/releases) for managing updates instead of using the redundant (?) UPDATES.json

Greetings

**Comment by ovflowd** [comment]
Yes is nice. But as a Free Plan, the API is limited for non-users usage.

If you try to use Github API from methods like Workers, "downloadString", etc. The endpoint will have a bandwith limit.

So this will make emulator crashes, if you reach limit. Or non valid - consistence data.

But if you're accessing API from browser, this will not happen. (Since if you're logged in)...

But is a good idea.

Also @TheDoct0r11 are you experiencing weird issues, like when try enter room, you being Disconnected?

**Comment by TheDoct0r11** [comment]
@sant0ro I've read up on the API Rate limits and as far as I can see, the limit counts per IP and not per Repository. [Source](https://developer.github.com/v3/#rate-limiting)

The only limit that exists for unauthorized requests is to use a User-Agent identiefing the application creating these requests [Source](https://developer.github.com/v3/#user-agent-required)

Also, one should always play it safe. Any Response not returning a 2XX status code should be caught so that the application keeps running.
Depending on the severity a warning should still be logged of course!

I haven't setup my database nor my client yet. I am running linux so I had to make the project build with mono first.

Now I'm just browsing the code to get a feeling for it and then I will probably setup my testing environment using [Vagrant](https://www.vagrantup.com/).

Also it might make sense to use a static analysis tool like [Gendarme](http://www.mono-project.com/docs/tools+libraries/tools/gendarme/)  (and integrate it into Travis) or [Coverity](https://scan.coverity.com/) to spot quite a number of issues in the code...

**Comment by ovflowd** [comment]
Sorry but i never used these Code Analysis Tools.
Also are useless for a Habbo Emulator, since the core is a crap. (but i changed a lot)
