### ISSUE TITLE
Yupi on linux

### ISSUE THREAD

**Issue by Killua99x** [sant0ro/Yupi#81]
@sant0ro  Can i use Yupi on linux with new build?

Despite the bugs I would use it on linux since for security reasons I'm posting all in place, even with mono and wine Yupi does not work, it's your decision, or else?

**Comment by ovflowd** [comment]
Wine wasn't made to do these stuffs. Also Wine emulates Windows XP, you need Windows 7 or higher.

Yupi works with Linux, as far i know, passed in TravisCI build. Use Mono 2.3

**Comment by Killua99x** [comment]
Thank you just can feel immediately, I have to use no cpu? or 32-bit?

**Comment by Killua99x** [comment]
I talked about wine because long ago I try azure and mono was not working but with wine turned and gave only a few mistakes in two .cs but nevertheless worked very well

**Comment by ovflowd** [comment]
Travis use 64bit architecture.

**Comment by Killua99x** [comment]
Thanks I'll try soon

**Comment by Killua99x** [comment]
@sant0ro  What is travis?

**Comment by Killua99x** [comment]
can i use mono up 2.3?

**Comment by Killua99x** [comment]
`root@:~# mono -V
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-10)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen`

**Comment by Killua99x** [comment]
http://prntscr.com/aj0e2v @sant0ro

**Comment by TheDoct0r11** [comment]
Wine uses Mono for .NET applications, so running Yupi with Wine or Mono should result in similar behaviour.

In my pull request  (#74) I've fixed the mono build, but just because mono does build the application, doesn't mean mono can also run it (on linux):

There are multiple reasons why Yupi won't run with mono:
1. Someone decided to hardcode directory paths in the code with backslashes, which linux handles as file names, not directory seperators. (Should be fixed in my fork)
2. There are still calls (P/Invoke) to user32.dll, which aim at removing the closing icon of the console. Since that doesn't make any sense in a no screen environment, I've simply deleted that code in my fork.
3. Any version of Mono prior to 3.12 doesn't contain SSL Root certificates, leading to the error as shown in the screenshot. [Source](http://www.mono-project.com/docs/faq/security/)
4. Use Mono 4! I doubt that any version of mono prior to 4.0 does support C#6/.NET 4.5

You might want to have a look at my [fork](https://github.com/TheDoct0r11/Yupi/tree/linux), but keep in mind that this is considered unstable, which is the reason why I didn't create a pull request yet.

(I'm currently working on reducing the amount of style and security issues reported by [Gendarme](https://cdn.rawgit.com/TheDoct0r11/Yupi/linux/gendarme.html) )

**Comment by Killua99x** [comment]
Thank you so much I feel now your fork @TheDoct0r11 
which I use? 64, 32 or No CPU?

@TheDoct0r11 http://prntscr.com/aj54vh

http://prntscr.com/aj55zs

Now i try on Linux

**Comment by TheDoct0r11** [comment]
You must run NuGet Restore first. Then Rebuild. 
Output should be in AnyCPU folder. 
Not sure, who decided to created that strange directory structure...

I forgot: Travis is a continuous integration platform. It will build every commit someone pushes to the repository, ensuring that the code can be compiled.

**Comment by Killua99x** [comment]
http://prntscr.com/aj5d0v

same error.. did I do something wrong?

**Comment by TheDoct0r11** [comment]
Are you still using mono 3.2?
I guess you're using the mono within the official debian repositories.
Follow the guidlines given [here](http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives) to install mono 4.0 (but before uninstall the old mono version)

**Comment by Killua99x** [comment]
i install Mono JIT compiler version 4.2.3  http://prntscr.com/ajc9gj

**Comment by Killua99x** [comment]
I cant use a start comand for start the emulator 

It does not work any command

**Comment by Killua99x** [comment]
It does not work any command

http://prntscr.com/ajcf6h

@TheDoct0r11 

http://prntscr.com/ajcxsk

**Comment by ovflowd** [comment]
Hi @TheDoct0r11 i will add you as Collaborator here. And you can continue the project. I have less time this month.

I'm sure May or June i will be back. But i'm 100% sure you will handle correctly smart decisions for this project.

You can add your credits in Emulator.

You will be collaborator now.

**Comment by ovflowd** [comment]
Closed Issue. Create a new. This Issue is so big..
